# FIXME: gcc not support fsanitize=memory
# cc_binary(
#     name = "uninitialized-memory-read",
#     srcs = [
#         "uninitialized-memory-read.cc",
#     ],
#     copts = [
#         "-g",
#         "-fno-omit-frame-pointer",
#         "-fsanitize=memory",
#     ],
#     linkopts = ["-fsanitize=memory"],
# )
