load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "process_overflow",
    srcs = [
        "process_overflow.cc",
    ],
    deps = [
        "@com_github_gflags_gflags//:gflags",
    ],
)

cc_binary(
    name = "thread_overflow",
    srcs = [
        "thread_overflow.cc",
    ],
    deps = [
        "@com_github_gflags_gflags//:gflags",
    ],
)
