/**
 * Autogenerated by Thrift for /home/curoky/repos/cpp/dumbo/dumbo/scaffold/serialization/fbthrift/mock.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "dumbo/scaffold/serialization/fbthrift/gen-cpp2/EchoService.h"
#include "dumbo/scaffold/serialization/fbthrift/gen-cpp2/EchoService.tcc"

namespace idl { namespace thrift { namespace cpp2 {
}}} // idl::thrift::cpp2
