/**
 * Autogenerated by Thrift for /home/curoky/repos/cpp/dumbo/dumbo/scaffold/serialization/fbthrift/mock.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "dumbo/scaffold/serialization/fbthrift/gen-cpp2/mock_data.h"

#include <thrift/lib/cpp2/gen/module_data_cpp.h>

namespace apache {
namespace thrift {


constexpr const std::size_t TEnumDataStorage<::idl::thrift::cpp2::EnumType>::size;
constexpr const std::array<::idl::thrift::cpp2::EnumType, 4> TEnumDataStorage<::idl::thrift::cpp2::EnumType>::values;
constexpr const std::array<folly::StringPiece, 4> TEnumDataStorage<::idl::thrift::cpp2::EnumType>::names;


constexpr const std::size_t TEnumDataStorage<::idl::thrift::cpp2::UnionType::Type>::size;
constexpr const std::array<::idl::thrift::cpp2::UnionType::Type, 2> TEnumDataStorage<::idl::thrift::cpp2::UnionType::Type>::values;
constexpr const std::array<folly::StringPiece, 2> TEnumDataStorage<::idl::thrift::cpp2::UnionType::Type>::names;


} // namespace thrift
} // namespace apache
