/**
 * Autogenerated by Thrift for
 * /home/curoky/repos/cpp/dumbo/dumbo/scaffold/serialization/fbthrift/mock.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "dumbo/scaffold/serialization/fbthrift/gen-cpp2/mock_data.h"

#include <thrift/lib/cpp2/gen/module_data_cpp.h>

namespace apache {
namespace thrift {

constexpr const std::size_t TEnumDataStorage<::idl::thrift::cpp2::EnumType>::size;
constexpr const std::array<::idl::thrift::cpp2::EnumType, 4>
    TEnumDataStorage<::idl::thrift::cpp2::EnumType>::values;
constexpr const std::array<folly::StringPiece, 4>
    TEnumDataStorage<::idl::thrift::cpp2::EnumType>::names;

constexpr const std::size_t TEnumDataStorage<::idl::thrift::cpp2::UnionType::Type>::size;
constexpr const std::array<::idl::thrift::cpp2::UnionType::Type, 2>
    TEnumDataStorage<::idl::thrift::cpp2::UnionType::Type>::values;
constexpr const std::array<folly::StringPiece, 2>
    TEnumDataStorage<::idl::thrift::cpp2::UnionType::Type>::names;

constexpr const std::size_t TStructDataStorage<::idl::thrift::cpp2::UnionType>::fields_size;
constexpr const std::array<folly::StringPiece,
                           TStructDataStorage<::idl::thrift::cpp2::UnionType>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::UnionType>::fields_names;
constexpr const std::array<int16_t, TStructDataStorage<::idl::thrift::cpp2::UnionType>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::UnionType>::fields_ids;
constexpr const std::array<apache::thrift::protocol::TType,
                           TStructDataStorage<::idl::thrift::cpp2::UnionType>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::UnionType>::fields_types;
constexpr const std::size_t TStructDataStorage<::idl::thrift::cpp2::MockRequest>::fields_size;
constexpr const std::array<folly::StringPiece,
                           TStructDataStorage<::idl::thrift::cpp2::MockRequest>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::MockRequest>::fields_names;
constexpr const std::array<int16_t,
                           TStructDataStorage<::idl::thrift::cpp2::MockRequest>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::MockRequest>::fields_ids;
constexpr const std::array<apache::thrift::protocol::TType,
                           TStructDataStorage<::idl::thrift::cpp2::MockRequest>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::MockRequest>::fields_types;
constexpr const std::size_t TStructDataStorage<::idl::thrift::cpp2::MockResponse>::fields_size;
constexpr const std::array<folly::StringPiece,
                           TStructDataStorage<::idl::thrift::cpp2::MockResponse>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::MockResponse>::fields_names;
constexpr const std::array<int16_t,
                           TStructDataStorage<::idl::thrift::cpp2::MockResponse>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::MockResponse>::fields_ids;
constexpr const std::array<apache::thrift::protocol::TType,
                           TStructDataStorage<::idl::thrift::cpp2::MockResponse>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::MockResponse>::fields_types;
constexpr const std::size_t TStructDataStorage<::idl::thrift::cpp2::MockException>::fields_size;
constexpr const std::array<folly::StringPiece,
                           TStructDataStorage<::idl::thrift::cpp2::MockException>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::MockException>::fields_names;
constexpr const std::array<int16_t,
                           TStructDataStorage<::idl::thrift::cpp2::MockException>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::MockException>::fields_ids;
constexpr const std::array<apache::thrift::protocol::TType,
                           TStructDataStorage<::idl::thrift::cpp2::MockException>::fields_size>
    TStructDataStorage<::idl::thrift::cpp2::MockException>::fields_types;

}  // namespace thrift
}  // namespace apache
