/**
 * Autogenerated by Thrift for /home/curoky/repos/cpp/dumbo/dumbo/scaffold/serialization/fbthrift/mock.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "dumbo/scaffold/serialization/fbthrift/gen-cpp2/mock_constants.h"

#include <thrift/lib/cpp2/gen/module_constants_cpp.h>


namespace idl { namespace thrift { namespace cpp2 {

constexpr char const * const mock_constants::GLOBAL_CONST_VAR_STRING_;

}}} // idl::thrift::cpp2
