/**
 * Autogenerated by Thrift for /home/curoky/repos/cpp/dumbo/dumbo/scaffold/serialization/fbthrift/mock.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "dumbo/scaffold/serialization/fbthrift/gen-cpp2/mock_types.h"

namespace idl { namespace thrift { namespace cpp2 {

struct mock_constants {

  // consider using folly::StringPiece instead of std::string whenever possible
  // to referencing this statically allocated string constant, in order to
  // prevent unnecessary allocations

  static constexpr char const * const GLOBAL_CONST_VAR_STRING_ = "123";

  static constexpr char const * GLOBAL_CONST_VAR_STRING() {
    return GLOBAL_CONST_VAR_STRING_;
  }

};

}}} // idl::thrift::cpp2
