/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mock_constants.h"

namespace idl { namespace thrift {

const mockConstants g_mock_constants;

mockConstants::mockConstants() {
  GLOBAL_CONST_VAR_STRING = "123";

}

}} // namespace

