/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mock_CONSTANTS_H
#define mock_CONSTANTS_H

#include "mock_types.h"

namespace idl { namespace thrift {

class mockConstants {
 public:
  mockConstants();

  std::string GLOBAL_CONST_VAR_STRING;
};

extern const mockConstants g_mock_constants;

}} // namespace

#endif
