name: unittest

on:
  schedule:
    - cron: '0 0 * * 1'
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CC: gcc-10
      CXX: g++-10

    steps:
      - uses: actions/checkout@v2
      - name: setup gcc 10
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10

      - name: show system info
        run: |
          gcc --version
          g++ --version
          gcc-10 --version
          g++-10 --version

      - name: setup bazel
        run: |
          brew tap curoky/tap
          # git -C $(brew --prefix)/Homebrew/Library/Taps/curoky/homebrew-tap checkout dev
          brew install bazel@3 tbb python@3.9 gperf qt@5.13.2 libiberty
          # sudo ln -s /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3 /usr/bin/python

      - name: mount bazel cache
        uses: actions/cache@v2
        with:
          path: '~/.cache/bazel'
          key: bazel-cache-${{ github.sha	}}
          restore-keys: |
            bazel-cache-

      - name: bazel clean
        if: ${{ github.event_name == 'schedule' }}
        run: rm -rf ~/.cache/bazel

      - name: bazel sync
        run: bazel sync

      - name: bazel build
        run: bazel build //...

      - name: bazel test
        run: bazel test //...
