name: unittest
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      CC: /home/linuxbrew/.linuxbrew/opt/gcc@10/bin/gcc-10
      CXX: /home/linuxbrew/.linuxbrew/opt/gcc@10/bin/g++-10

    steps:
      - uses: actions/checkout@v2

      - name: setup bazel
        run: |
          brew tap curoky/tap
          # git -C $(brew --prefix)/Homebrew/Library/Taps/curoky/homebrew-tap checkout dev
          brew install bazel@3 gcc@10 tbb python gperf qt@5.13.2 libaio libiberty

      - name: mount bazel cache
        uses: actions/cache@v2
        with:
          path: |
            '/home/runner/.cache/bazel'
            '/home/curoky/.cache/Homebrew'
          key: bazel-cache-${{ github.sha	}}
          restore-keys: |
            bazel-cache-

      - name: bazel build
        run: bazel build //...

      - name: bazel test
        run: bazel test //...
