name: unittest
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: curoky/homebrew:ubunut20.10

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      PATH: /home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin

    steps:
      - uses: actions/checkout@v2

      - name: setup bazel
        run: |
          brew tap curoky/tap
          # git -C $(brew --prefix)/Homebrew/Library/Taps/curoky/homebrew-tap checkout dev
          brew install bazel@3 tbb python@3.9 gperf qt@5.13.2 libiberty
          sudo ln -s /home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3 /usr/bin/python

      - name: mount bazel cache
        uses: actions/cache@v2
        with:
          path: '~/.cache/bazel'
          key: bazel-cache-${{ github.sha	}}
          restore-keys: |
            bazel-cache-

      # - name: bazel clean
      #   if: ${{ github.event_name == 'schedule' }}
      #   run: rm -rf ~/.cache/bazel

      - name: bazel build
        run: bazel build //...

      - name: bazel test
        run: bazel test //...
