name: unittest
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      CC: /home/linuxbrew/.linuxbrew/bin/gcc-10

    steps:
      - uses: actions/checkout@v2

      - name: install depend packages
        run: sudo apt-get install -y libiberty-dev qt5-default libaio-dev

      - name: setup bazel
        run: |
          brew tap curoky/tap --shallow
          brew install bazel@3 gcc@10 tbb

      - name: mount bazel cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/.cache/bazel'
          key: bazel

      - name: bazel build
        run: bazel build //...

      - name: bazel test
        run: bazel test //...
