name: unittest

on:
  schedule:
    - cron: '0 0 * * 1'
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: curoky/compile:ubuntu21.04

    steps:
      - uses: actions/checkout@v2
      - name: setup bazel
        run: |
          brew install bazel@3 tbb qt@5.13.2 libiberty
          brew reinstall qt@5.13.2

      - name: bazel build
        run: bazel build //...

      - name: bazel test
        run: bazel test //...

      - uses: curoky/actions/tmate@master
        if: ${{ failure() }}
